### ISSUE TITLE
Windows: After installing features, sometimes can't delete Liberty dir

### ISSUE THREAD

**Issue by ericglau** [OpenLiberty/ci.gradle#402] opened 2019-12-18 19:22 UTC
1. Use the latest Liberty Gradle Plugin development snapshot and the latest Open Liberty 20.0.0.1 build.
2. Run `gradle clean libertyCreate installFeature clean --info`

The following error sometimes occurs (but sometimes it doesn't occur and the clean is successful):
```
> java.io.IOException: Unable to delete directory 'C:\Users\Eric\git\demo-devmode\build'
    Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
    - C:\Users\Eric\git\demo-devmode\build\wlp\lib\com.ibm.ws.install_1.0.36.jar
    - C:\Users\Eric\git\demo-devmode\build\wlp\lib
    - C:\Users\Eric\git\demo-devmode\build\wlp
```

This appears to only occur on Windows.  It does not occur on Mac OS.

Steps to reproduce:
1. Build ci.common and ci.gradle from the latest source.
1. Clone https://github.com/OpenLiberty/demo-devmode
1. In build.gradle, change the `buildscript` section to:
```
buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
    }
    dependencies {
        classpath 'io.openliberty.tools:liberty-gradle-plugin:3.0-SNAPSHOT'
    }
}
```
4. In ci.gradle's build.gradle, change the `dependencies` section to update the ci.common reference and rebuild.
```
dependencies {
    ...
    compile ('io.openliberty.tools:ci.common:1.8.3-SNAPSHOT')
```
5. Download an Open Liberty 20.0.0.1 kernel.  For example, use [this kernel build from 2020-01-06](https://ibm.box.com/s/056kcxcrcmkehf3jdhk7e1gwxijc5pvi).  Extract it and edit `wlp\lib\versions\openliberty.properties` to use version 19.0.0.12 so that it can get features from Maven Central, then zip it back up.   Add the following to build.gradle and edit its path to point to your build.
```
liberty {
      install {
          runtimeUrl="file:///Users/eric/Downloads/wlp.zip"
      }
}
```
6. Run `gradle clean libertyCreate installFeature clean --info` several times.  If using Windows, sometimes the `Unable to delete directory` error appears, after which you need to terminate the Java process before being able to delete the `build` dir in your project.

**Comment by ericglau** [comment] 2020-01-07 19:43
Related to https://github.com/OpenLiberty/ci.gradle/issues/397, which fixed a larger resource leak using PRs https://github.com/OpenLiberty/ci.common/pull/122 and https://github.com/OpenLiberty/open-liberty/pull/10200.  But even with those fixes, `com.ibm.ws.install_1.0.36.jar` is still sometimes being held here.

**Comment by turkeylurkey** [comment] 2020-01-23 20:37
Liberty issue opened to track this problem:
https://github.com/OpenLiberty/open-liberty/issues/10562

**Comment by turkeylurkey** [comment] 2020-02-07 22:03
The problem is that URLConnection object keeps a cache which references the jar file even after close() is called on the URLClassLoader. This reference prevents Windows from closing the file.  The issue appears intermittent because sometimes the cache is cleared.

There is a fix for Java 9 and higher: `URLConnection.setDefaultUseCaches​("jar", false)`
In order for the code to continue to work on Java 8 we will use reflection to call the appropriate methods. Since there is no fix for Java 8 on Windows, users will have to use the `--no-daemon` command line option or the gradle.properties `org.gradle.daemon=false`

**Closed** 2020-02-13 15:37 UTC
